### ISSUE TITLE
[Question] Mouse Finder Right Click Menu Options

### ISSUE THREAD

**Issue by 3raxton** [neilsardesai/Mouse-Finder#5]
Hey @neilsardesai, great work on Mouse Finder. I remember when you shared it on Twitter and since its been such a powerful addition to my Mac. I'm curious if it is somehow possible to have Mouse Finder show the recent files, locations, Go to Folder, New Finder Window, etc. within Mouse Finder as seen attached from the regular Finder. 

I'm a heavy Finder user relying on these shortcuts. Do you know if it is possible to do something like this? Again, great work on Mouse Finder, keep up the great work! 🎉 (also sweet slider, love your tweets of what you're working on) 

![image](https://user-images.githubusercontent.com/20716142/153722227-829c6fc7-b7d2-406e-bc53-9c5d87b2e794.png)

**Comment by neilsardesai** [comment]
Hey Braxton!
I’m not sure if adding these shortcuts is possible, but I’ll look into it. I’d also welcome any PR that adds this functionality.

**Comment by 3raxton** [comment]
Hey Neil, 

Thanks for your reply, I appreciate it. I wanted to point out an issue I'd been facing that I DMed you on Twitter (@3raxton). 

Would you mind taking a look at the way Finder is blinking there and providing me with any thoughts?

Thanks!
